name: CI
on: [push]

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login 192.168.1.41:3000 --username "${{ github.actor }}" --password-stdin
          
      - name: Build and Push UI
        run: |
          docker build -t 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-ui:latest .
          docker push 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-ui:latest
          
      - name: Build and Push Worker
        run: |
          docker build -t 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-worker:latest .
          docker push 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-worker:latest
          
      - name: Build and Push AI
        run: |
          docker build -t 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-ai:latest .
          docker push 192.168.1.41:3000/${{ github.repository_owner }}/${{ github.event.repository.name }}/npm-ai:latest
