name: CI
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Get Version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=latest
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login 192.168.1.41:3000 --username "${{ github.actor }}" --password-stdin
          
      - name: Build and Push UI
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BASE_TAG="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/npm-ui"
          
          docker build -t "${BASE_TAG}:${VERSION}" .
          docker push "${BASE_TAG}:${VERSION}"
          
          if [ "$VERSION" != "latest" ]; then
            docker tag "${BASE_TAG}:${VERSION}" "${BASE_TAG}:latest"
            docker push "${BASE_TAG}:latest"
          fi
          
      - name: Build and Push Log Worker
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BASE_TAG="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/npm-log-worker"
          
          docker build -t "${BASE_TAG}:${VERSION}" .
          docker push "${BASE_TAG}:${VERSION}"
          
          if [ "$VERSION" != "latest" ]; then
            docker tag "${BASE_TAG}:${VERSION}" "${BASE_TAG}:latest"
            docker push "${BASE_TAG}:latest"
          fi
          
      - name: Build and Push Cron Worker
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BASE_TAG="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/npm-cron-worker"
          
          docker build -t "${BASE_TAG}:${VERSION}" .
          docker push "${BASE_TAG}:${VERSION}"
          
          if [ "$VERSION" != "latest" ]; then
            docker tag "${BASE_TAG}:${VERSION}" "${BASE_TAG}:latest"
            docker push "${BASE_TAG}:latest"
          fi
          
      - name: Build and Push AI
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BASE_TAG="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/npm-ai"
          
          docker build -t "${BASE_TAG}:${VERSION}" .
          docker push "${BASE_TAG}:${VERSION}"
          
          if [ "$VERSION" != "latest" ]; then
            docker tag "${BASE_TAG}:${VERSION}" "${BASE_TAG}:latest"
            docker push "${BASE_TAG}:latest"
          fi
          
      - name: Build and Push API
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BASE_TAG="192.168.1.41:3000/${REPO_OWNER}/${REPO_NAME}/npm-api"
          
          docker build -t "${BASE_TAG}:${VERSION}" .
          docker push "${BASE_TAG}:${VERSION}"
          
          if [ "$VERSION" != "latest" ]; then
            docker tag "${BASE_TAG}:${VERSION}" "${BASE_TAG}:latest"
            docker push "${BASE_TAG}:latest"
          fi
